// import { Link } from "react-router-dom";
import Layout from "./Layout";
// import LoadingPage from "./LoadingPage";
import shot from '../assets/shot.png'
import divider from '../assets/divider.png'
import autoreccli from '../assets/autoreccli.png'

const Projects = () => {
  return (
    <Layout>
      <div className="flex flex-col space-y-20 pb-10 ">
        <div className="flex flex-row h-full  w-5/6 self-center">
          <div className=" border-green-900 text-gray-400 px-2 space-y-5 basis-1/2  ">
            <div>
            <a
              href="https://github.com/aspasht/shot"
              className="text-[96px] font-righteous underline underline-offset-8 text-orange-500 opacity-70"
            >
              shot 
            </a>
            <p className="py-2 text-gray-600">[ Command Line Tool ]</p>
            <h2 className="text-3xl font-arapey py-2 text-green-900">
              Automate the process of capturing screenshots from a list of URLs.
            </h2>
            <p>This tool designed to automate the process of taking screenshots of web pages from a given list of URLs. This tool reads URLs from a specified file, captures full-page screenshots, and saves them to a designated directory. It is ideal for web developers, QA testers, digital marketers, and anyone needing to document or analyze web pages.</p>
            </div>
            <div className="">
              <h1 className="text-xl font-righteous underline">Stack used</h1>
              <div className="px-8">
                <li><a href="https://go.dev/" >Go</a></li>
                <li><a href="https://github.com/spf13/cobra" >Cobra (go library)</a></li>
              </div>
            </div>
          </div>
    
          <div className="w-full basis-1/2 py-8">
            <img className="w-full object-fill " src={shot} ></img>
          </div>
        </div>
      <div className="border mx-48 border-dotted border-green-950"></div>

        <div className="flex flex-row-reverse h-full w-5/6 self-center gap-2 ">
          <div className=" border-green-900 text-gray-400 px-12 space-y-5 basis-1/2">
            <div>
            <a
              href="https://github.com/aspasht/divider"
              className="text-[96px] font-righteous underline underline-offset-8 text-orange-500 opacity-70"
            >
              divider 
            </a>
            <p className="py-2 text-gray-600">[ Command Line Tool ]</p>
            <h2 className="text-3xl font-arapey py-2 text-green-900">
            Gather interesting urls with extensions from a given file.
            </h2>
            <p>This will process files generated by tools like waybackurls,gau,etc containing urls and grab only urls ending with interesting file extensions.  </p>
            </div>
            <div className="">
              <h1 className="text-xl font-righteous underline">Stack used</h1>
              <div className="px-8">
                <li><a href="https://www.python.org/" >Python</a></li>
                <li><a href="https://www.gnu.org/software/bash/manual/" >Shell</a></li>
              </div>
            </div>
          </div>

          <div className="w-full basis-1/2  py-8">
            <img className="w-full h-full object-fill " src={divider} ></img>
          </div>
        </div>

        <div className="border mx-48 border-dotted border-green-950"></div>
        <div className="flex h-full  w-5/6 self-center gap-2">
          <div className=" border-green-900 text-gray-400 p-2 space-y-5 basis-1/2  ">
            <div>
            <a
              href="https://github.com/aspasht/autoreccli"
              className="text-[96px] font-righteous underline underline-offset-8 text-orange-500 opacity-70"
            >
              autoreccli 
            </a>
            <p className="py-2 text-gray-600">[ Command Line Tool ]</p>
            <h2 className="text-3xl font-arapey py-2 text-green-900">
              Recon tool for Bug Bounty Hunters and Penetration Testers.
            </h2>
            <div className="w-full border p-2 bg-gray-800 rounded-md mb-2">
            <code className="w-full font-bold text-green-500 font-arapey"><strong className="text-green-500 opacity-50">$</strong> go install github.com/Aspasht/autoreccli@latest</code>
            </div>
            <p className=" font-sans">Autoreccli is a command-line utility designed for streamlining reconnaissance tasks by integrating various powerful tools such as subfinder, amass, assetfinder, getJS, waybackurls, gau, and more.</p>
            </div>
            <div className="">
              <h1 className="text-xl font-righteous underline">Stack used</h1>
              <div className="px-8">
                <li><a href="https://go.dev/" >Go</a></li>
                <li><a href="https://github.com/spf13/cobra" >Cobra (go library)</a></li>
              </div>
            </div>
          </div>

          <div className=" basis-1/2  py-8">
            <img className="w-full  object-fill" src={autoreccli} ></img>
          </div>
        </div>
     

      </div>
    </Layout>
  );
};

export default Projects;
